### ISSUE TITLE
Support OMPR

### ISSUE THREAD

**Issue by harryprince** [r-simmer/simmer.optim#12]
[ompr](https://github.com/dirkschumacher/ompr) is great tidy interface for MILP problem. Integrate with ompr might be a good way.

* https://github.com/dirkschumacher/ompr

**Comment by Enchufa2** [comment]
I don't see how `simmer.optim` could support `ompr`. As I see it, MILP and DES are alternatives for certain problems: you either use one or the other. You may use both and compare the results, but there's no way of "mixing" them.
