### ISSUE TITLE
Grid optimisation will produce unstable solutions if minima/maxima are non-unique depending on how the grid of parameters is set up

### ISSUE THREAD

**Issue by k0fzofs3xh** [r-simmer/simmer.optim#13]
The grid optimisation algorithm will choose the first solution in the search grid that meets the constraints. If there are multiple combinations of parameters where the objective function is minimised (or maximised), then the "first" combination is always chosen as `which.min` is used. The solution will therefore depend purely on how the grid of parameters was set up.

**Comment by Enchufa2** [comment]
I don't see how this is an issue specific to grid optimisation. If minima/maxima are not unique, the solution will be unstable regardless of the algorithm, and will depend on the initialisation.
